import { noteHtmlResetStyle } from '../components/note-html';
import type { WebviewTheme } from '../webview-theme';

export function installX6Styles(theme: WebviewTheme): void {
	const styleId = 'ontology-diagram-editor-x6-styles';
	const existingStyle = document.getElementById(styleId);
	const style = existingStyle instanceof HTMLStyleElement ? existingStyle : document.createElement('style');
	style.id = styleId;
	style.textContent = [
		'.x6-graph {',
		'  position: relative;',
		'  overflow: hidden;',
		'  outline: none;',
		'  touch-action: none;',
		'}',
		'.x6-graph-svg,',
		'.x6-graph-svg-stage {',
		'  position: absolute;',
		'  inset: 0;',
		'}',
		'.x6-node { cursor: move; }',
		'.x6-edge { cursor: pointer; }',
		'.x6-edge .connection { stroke-linejoin: round; }',
		'.x6-edge .tools { opacity: 1; }',
		'.ontology-single-edge-selection .x6-widget-selection-box-edge {',
		'  display: none !important;',
		'}',
		'.x6-edge-tool-source-anchor circle,',
		'.x6-edge-tool-target-anchor circle,',
		'.x6-edge-tool-segment rect {',
		`  fill: ${theme.editorForeground};`,
		`  stroke: ${theme.editorBackground};`,
		'  stroke-width: 2;',
		'}',
		'.x6-widget-selection {',
		'  position: absolute;',
		'  top: 0;',
		'  left: 0;',
		'  display: none;',
		'  width: 0;',
		'  height: 0;',
		'  touch-action: none;',
		'}',
		'.x6-widget-selection-selected {',
		'  display: block;',
		'}',
		'.x6-widget-selection-rubberband {',
		'  display: block;',
		`  background-color: ${theme.focusBorder};`,
		`  border: 1px solid ${theme.focusBorder};`,
		'  opacity: 0.25;',
		'}',
		'.x6-widget-selection-box,',
		'.x6-widget-selection-inner {',
		'  box-sizing: content-box !important;',
		'  margin-top: -5px;',
		'  margin-left: -5px;',
		'  padding-right: 8px;',
		'  padding-bottom: 8px;',
		`  border: 2px solid ${theme.focusBorder};`,
		'  box-shadow: none;',
		'}',
		'.x6-widget-transform {',
		'  position: absolute;',
		'  box-sizing: content-box !important;',
		'  margin: -5px 0 0 -5px;',
		'  padding: 4px;',
		`  border: 1px dashed ${theme.focusBorder};`,
		'  border-radius: 4px;',
		'  pointer-events: none;',
		'  user-select: none;',
		'}',
		'.x6-widget-transform > div {',
		'  position: absolute;',
		'  box-sizing: border-box;',
		'  width: 8px;',
		'  height: 8px;',
		`  border: 1px solid ${theme.focusBorder};`,
		`  background: ${theme.editorBackground};`,
		'  border-radius: 50%;',
		'  pointer-events: auto;',
		'}',
		'.x6-widget-transform-resize[data-position="top-left"] { top: -4px; left: -4px; cursor: nwse-resize; }',
		'.x6-widget-transform-resize[data-position="top-right"] { top: -4px; right: -4px; cursor: nesw-resize; }',
		'.x6-widget-transform-resize[data-position="bottom-left"] { bottom: -4px; left: -4px; cursor: nesw-resize; }',
		'.x6-widget-transform-resize[data-position="bottom-right"] { right: -4px; bottom: -4px; cursor: nwse-resize; }',
		'.x6-widget-transform-resize[data-position="top"] { top: -4px; left: 50%; margin-left: -4px; cursor: ns-resize; }',
		'.x6-widget-transform-resize[data-position="bottom"] { bottom: -4px; left: 50%; margin-left: -4px; cursor: ns-resize; }',
		'.x6-widget-transform-resize[data-position="left"] { top: 50%; left: -4px; margin-top: -4px; cursor: ew-resize; }',
		'.x6-widget-transform-resize[data-position="right"] { top: 50%; right: -4px; margin-top: -4px; cursor: ew-resize; }',
		'.x6-widget-transform-rotate,',
		'.x6-widget-transform.no-rotate .x6-widget-transform-rotate {',
		'  display: none;',
		'}',
		'.x6-widget-selection-box,',
		'.x6-widget-selection-inner {',
		`  border-color: ${theme.focusBorder} !important;`,
		'  box-shadow: none !important;',
		'}',
		'.x6-widget-transform {',
		`  border-color: ${theme.focusBorder} !important;`,
		'  border-radius: 4px !important;',
		'}',
		'.x6-widget-transform > div {',
		`  border-color: ${theme.focusBorder} !important;`,
		`  background: ${theme.editorBackground} !important;`,
		'}',
		noteHtmlResetStyle(),
	].join('\n');
	if (existingStyle === null) {
		document.head.appendChild(style);
	}
}


