import { BorderStyle, CommonStyle, EdgeStyle, FontStyle, LabelStyle } from '../odiagram';
import { CanvasStyle, OntologyDiagramTheme, OntologyDiagramThemeStyleSet } from './otheme-document';

export const defaultOntologyDiagramTheme = new OntologyDiagramTheme(
	new CommonStyle(
		'#FFFFCC',
		'#000000',
		new FontStyle('Arial', false, false, 12),
		new BorderStyle('solid', 1, '#333333'),
		{},
		0,
		true,
	),
	new EdgeStyle(
		'#4A4A4A',
		'solid',
		1,
		'#000000',
		new FontStyle('Arial', false, false, 10),
	),
	new CommonStyle(
		'#CCFFCC',
		'#000000',
		new FontStyle('Arial', false, false, 11),
		new BorderStyle('solid', 1, '#669966'),
		{},
		0,
		true,
	),
	new LabelStyle(
		'#000000',
		new FontStyle('Arial', false, false, 12),
	),
	{},
	{},
	new CanvasStyle('#FFFFFF'),
	new OntologyDiagramThemeStyleSet(
		new CanvasStyle('#FFFFFF'),
		new CommonStyle(
			'#FFFFCC',
			'#000000',
			new FontStyle('Arial', false, false, 12),
			new BorderStyle('solid', 1, '#333333'),
			{},
			0,
			true,
		),
		new EdgeStyle(
			'#4A4A4A',
			'solid',
			1,
			'#000000',
			new FontStyle('Arial', false, false, 10),
		),
		new CommonStyle(
			'#CCFFCC',
			'#000000',
			new FontStyle('Arial', false, false, 11),
			new BorderStyle('solid', 1, '#669966'),
			{},
			0,
			true,
		),
		new LabelStyle(
			'#000000',
			new FontStyle('Arial', false, false, 12),
		),
	),
	new OntologyDiagramThemeStyleSet(
		new CanvasStyle('#0F172A'),
		new CommonStyle(
			'#1E293B',
			'#F1F5F9',
			new FontStyle('Arial', false, false, 12),
			new BorderStyle('solid', 1, '#475569'),
			{},
			0,
			true,
		),
		new EdgeStyle(
			'#94A3B8',
			'solid',
			1.5,
			'#E2E8F0',
			new FontStyle('Arial', false, false, 10),
		),
		new CommonStyle(
			'#292524',
			'#FDE68A',
			new FontStyle('Arial', false, false, 11),
			new BorderStyle('dashed', 1, '#78716C'),
			{},
			0,
			true,
		),
		new LabelStyle(
			'#E2E8F0',
			new FontStyle('Arial', false, false, 12),
		),
	),
);
