import { BorderStyle, CommonStyle, EdgeStyle, FontStyle, LabelStyle } from '../odiagram';
import { CanvasStyle, OntologyDiagramTheme, OntologyDiagramThemeStyleSet } from './otheme-document';

export const defaultOntologyDiagramTheme = new OntologyDiagramTheme(
	new CommonStyle(
		'#FFFFFF',
		'#1E293B',
		new FontStyle('Arial', false, false, 12),
		new BorderStyle('solid', 1, '#CBD5E1'),
		{},
		8,
		true,
	),
	new EdgeStyle(
		'#8795A8',
		'solid',
		1.25,
		'#475569',
		new FontStyle('Arial', false, false, 10),
	),
	new CommonStyle(
		'#FFF8DC',
		'#493D1F',
		new FontStyle('Arial', false, false, 11),
		new BorderStyle('solid', 1, '#E7CA72'),
		{},
		8,
		true,
	),
	new LabelStyle(
		'#1E293B',
		new FontStyle('Arial', false, false, 12),
	),
	{},
	{},
	new CanvasStyle('#F5F7FA'),
	new OntologyDiagramThemeStyleSet(
		new CanvasStyle('#F5F7FA'),
		new CommonStyle(
			'#FFFFFF',
			'#1E293B',
			new FontStyle('Arial', false, false, 12),
			new BorderStyle('solid', 1, '#CBD5E1'),
			{},
			8,
			true,
		),
		new EdgeStyle(
			'#8795A8',
			'solid',
			1.25,
			'#475569',
			new FontStyle('Arial', false, false, 10),
		),
		new CommonStyle(
			'#FFF8DC',
			'#493D1F',
			new FontStyle('Arial', false, false, 11),
			new BorderStyle('solid', 1, '#E7CA72'),
			{},
			8,
			true,
		),
		new LabelStyle(
			'#1E293B',
			new FontStyle('Arial', false, false, 12),
		),
	),
	new OntologyDiagramThemeStyleSet(
		new CanvasStyle('#0F172A'),
		new CommonStyle(
			'#1E293B',
			'#F1F5F9',
			new FontStyle('Arial', false, false, 12),
			new BorderStyle('solid', 1, '#475569'),
			{},
			0,
			true,
		),
		new EdgeStyle(
			'#94A3B8',
			'solid',
			1.5,
			'#E2E8F0',
			new FontStyle('Arial', false, false, 10),
		),
		new CommonStyle(
			'#292524',
			'#FDE68A',
			new FontStyle('Arial', false, false, 11),
			new BorderStyle('dashed', 1, '#78716C'),
			{},
			0,
			true,
		),
		new LabelStyle(
			'#E2E8F0',
			new FontStyle('Arial', false, false, 12),
		),
	),
);
