import { BorderStyle, CommonStyle, EdgeStyle, FontStyle, LabelStyle } from '../odiagram';
import { CanvasStyle, OntologyDiagramTheme, OntologyDiagramThemeStyleSet } from './otheme-document';

export const defaultOntologyDiagramTheme = new OntologyDiagramTheme(
	new CommonStyle(
		'#FFFFCC',
		'#000000',
		new FontStyle('Arial', false, false, 12),
		new BorderStyle('solid', 1, '#333333'),
		{},
		0,
		true,
	),
	new EdgeStyle(
		'#4A4A4A',
		'solid',
		1,
		'#000000',
		new FontStyle('Arial', false, false, 10),
	),
	new CommonStyle(
		'#CCFFCC',
		'#000000',
		new FontStyle('Arial', false, false, 11),
		new BorderStyle('solid', 1, '#669966'),
		{},
		0,
		true,
	),
	new LabelStyle(
		'#000000',
		new FontStyle('Arial', false, false, 12),
	),
	{},
	{},
	new CanvasStyle('#FFFFFF'),
	new OntologyDiagramThemeStyleSet(
		new CanvasStyle('#FFFFFF'),
		new CommonStyle(
			'#FFFFCC',
			'#000000',
			new FontStyle('Arial', false, false, 12),
			new BorderStyle('solid', 1, '#333333'),
			{},
			0,
			true,
		),
		new EdgeStyle(
			'#4A4A4A',
			'solid',
			1,
			'#000000',
			new FontStyle('Arial', false, false, 10),
		),
		new CommonStyle(
			'#CCFFCC',
			'#000000',
			new FontStyle('Arial', false, false, 11),
			new BorderStyle('solid', 1, '#669966'),
			{},
			0,
			true,
		),
		new LabelStyle(
			'#000000',
			new FontStyle('Arial', false, false, 12),
		),
	),
	new OntologyDiagramThemeStyleSet(
		new CanvasStyle('#111827'),
		new CommonStyle(
			'#1F2937',
			'#F9FAFB',
			new FontStyle('Arial', false, false, 12),
			new BorderStyle('solid', 1, '#4B5563'),
			{},
			8,
			true,
		),
		new EdgeStyle(
			'#CBD5E1',
			'solid',
			1.25,
			'#F9FAFB',
			new FontStyle('Arial', false, false, 10),
		),
		new CommonStyle(
			'#3F371A',
			'#FDE68A',
			new FontStyle('Arial', false, false, 11),
			new BorderStyle('dashed', 1, '#A16207'),
			{},
			6,
			true,
		),
		new LabelStyle(
			'#F9FAFB',
			new FontStyle('Arial', false, false, 12),
		),
	),
);
